services:
  - type: web
    name: genetic-algorithm-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: "https://your-app-name.netlify.app"